# Generated by Django 3.0 on 2021-06-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinfo',
            name='quantity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicineinfo',
            name='remaining_tablets',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='pomid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.MedicineInfo'),
        ),
        migrations.DeleteModel(
            name='Contains',
        ),
    ]
