# Generated by Django 3.0 on 2021-06-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20210607_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='required_tablets',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='OrgRequires',
        ),
    ]
