# Generated by Django 3.0 on 2021-06-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20210607_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinfo',
            name='days_count',
            field=models.IntegerField(),
        ),
    ]
