# Generated by Django 3.0 on 2021-06-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_auto_20210609_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinfo',
            name='days_count',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
