# Generated by Django 3.0 on 2021-06-09 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_auto_20210609_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='oid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
