from django.urls import path
from Student import views
from django.contrib.auth import views as v
urlpatterns=[
	path('',views.management,name="mag"),
	path('home/',views.HomePage,name="home"),
	path('login/',v.LoginView.as_view(template_name="htfiles/login.html"),name="lg"),
	path('logout/',v.LogoutView.as_view(template_name='htfiles/logout.html'),name="logo"),
	# path('registration/',views.registration,name="reg"),
	path('registration1/',views.registration1,name="nreg"),
	path('main/',views.mainpage,name="mn"),
	path('chpwd/',views.cgf,name="cg"),
	path('reset/',v.PasswordResetView.as_view(template_name="htfiles/resetpassword.html"),name="reset_password"),
	path('rst_done/',v.PasswordResetDoneView.as_view(template_name='htfiles/resetpassworddone.html'),name="password_reset_done"),
	path('ret_cf/<uidb64>/<token>/',v.PasswordResetConfirmView.as_view(template_name='htfiles/resetpasswordconfirm.html'),name="password_reset_confirm"),
	path('rst_cmplt/',v.PasswordResetCompleteView.as_view(template_name="htfiles/reset_password_complete.html"),name="password_reset_complete"),
	path('role/',views.role,name="ro"),
	path('rlreq/',views.rolereq,name="rq"),
	path('userpage/',views.userpage,name="up"),
	path('pfe/',views.profile,name="pf"),
	path('orgf/',views.orgform,name="og"),
	path('upfle/',views.updpfle,name="upf"),
	path('dnprf/',views.dnrpfle,name="dntpf"),
	path('cr/',views.crud,name="crud"),
	path('tb/',views.tab,name="tab"),
	path('del/<str:id>',views.deletedata,name="delete"),
	path('delete/<int:id>',views.delete,name="del"),
	path('e/<int:si>/',views.userupdate,name="ue"),
	path('view/',views.view,name="vi"),
	path('gvperm/',views.gvper,name="gv"),
	path('aprrl/<int:t>/',views.aprvrl,name="apr"),
	path('in/',views.index1,name="inx"),
	path('prm/',views.peruser,name="pmu"),
	path('about/',views.about,name="ab"),
	path('rq/<int:id>/',views.requ,name="rqt"),
	path('srchbar/',views.search,name="srch"),
	path('expirytab/',views.expirytab,name="expt"),
	path('details/',views.details,name="details"),
]